language: go
sudo: false
go:
  - master
before_install:
  - go get github.com/mattn/goveralls
before_script:
  - go get github.com/minio/minio
  - export PATH=$PATH:$HOME/gopath/bin
script:
  - go test -v -coverprofile=muxfys.coverprofile -covermode count .
  - goveralls -coverprofile=muxfys.coverprofile -service travis-ci
